# Generated by Django 4.1.7 on 2023-04-02 14:09

from django.contrib.auth.hashers import make_password
from django.db import migrations


def default_superuser(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.create(
        username="admin",
        is_superuser=True,
        is_staff=True,
        password=make_password("admin"),
        email="admin@admin.com",
        first_name="Admin",
        last_name="Admin",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_superuser, migrations.RunPython.noop),
    ]
