# Generated by Django 4.2 on 2023-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mocker", "0003_alter_server_base_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="full_path",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
