# Generated by Django 4.2 on 2023-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mocker", "0005_endpoint_is_active_alter_endpoint_endpoint_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="response_body",
            field=models.TextField(blank=True),
        ),
    ]
