# Generated by Django 4.2 on 2025-01-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mocker", "0006_alter_endpoint_response_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="run_python_code",
            field=models.BooleanField(
                default=False,
                help_text="When checked, define a function 'evaluate' in the response body that returns data.",
            ),
        ),
    ]
