# Generated by Django 4.2 on 2025-01-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mocker", "0006_alter_endpoint_response_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="python_code",
            field=models.TextField(
                blank=True, help_text="Python code to be executed for this endpoint"
            ),
        ),
    ]
