name: Push code to CodeCommit

on:
  push:
    branches: ["main"]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_REPO: ${{ secrets.AWS_REPO }}

        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          git remote add codecommit${{ secrets.AWS_REPO}}
          git push codecommit master
